# yaml Go dep: go get gopkg.in/yaml.v2

# AppD controller
controller: 
# AppD port
port: 
# true or false
ssl: 
# AppD analytics endpoint
analyticsEndPoint: 
# AppD global account name on license page
globalAccountName: 
# unique key from analytics
analyticsKey: 
# this will be the name of the custom schema for APIM in AppD
analyticsGatewaySchema: 
# this will be the name of the custom schema for CosmosDB in AppD
analyticsCosmosSchema:

azureSubscriptionId: 
azureEventHubNameSpace: 
azureEventHubConnString: 
azureClientID: 
azureClientSecret: 
azureTenantID: 
# if you're not monitoring APIM, set this to nil
azureGatewayHubName: nil
# if you're not monitoring CosmosDB, set this to nil
azureCosmosHubName: nil
azureResourceGroup: 