# AppD analytics endpoint
analyticsEndPoint: 
# AppD global account name on license page
globalAccountName: 
# unique key from analytics
analyticsKey: 
# this will be the name of the custom schema for APIM in AppD
analyticsGatewaySchema: 
# this will be the name of the custom schema for CosmosDB in AppD
analyticsCosmosSchema:

# subscriptionId is the Azure Subscription ID 
azureSubscriptionId: 
# Application ID for your application via Access Control (IAM)
azureClientID: 
# client secret is available in the keys section for app registrations
azureClientSecret: 
# tenantId is the Azure Active Directory “Directory ID”

# EventHub namespace
azureEventHubNameSpace: 
# EventHub conneciton string
azureEventHubConnString: 
# Name of the resource group
azureResourceGroup: 

# if you're not monitoring APIM, set this to nil
azureGatewayHubName: nil
# if you're not monitoring CosmosDB, set this to nil
azureCosmosHubName: nil
